# Generated by Django 5.1.7 on 2025-03-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
