# Generated by Django 5.1.7 on 2025-03-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='laptop_uuid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_uuid',
        )
    ]
