# Generated by Django 5.1.7 on 2025-03-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0002_rename_student_studentinfo'),
        ('users', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='laptop_uuid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_uuid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='attendance_management.studentinfo'),
        ),
    ]
