# Generated by Django 5.1.7 on 2025-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
