# Generated by Django 5.1.7 on 2025-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_customuser_slug_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_first_last_name',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('slug_name',), name='unique_slug_name'),
        ),
    ]
