# Generated by Django 5.1.7 on 2025-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
