# Docker Compose file for development setup
version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    # Uncomment below if you want to wait for db
    # depends_on:
    #   - db

# Add a db service if needed, e.g. for Postgres
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: mydb
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata: