erDiagram
    User {
        string id
        string name
        string role_id FK
        string student_info_id FK
        string email
        string phone
        string password_hash
    }
    Notification {
        string id
        string msg
        string system_type
        string status
        datetime created_at
        datetime updated_at
    }
    Attendance_record {
        string id
        datetime check_in_time
        datetime check_out_time
        float long
        float lat
        string status
        string student_id FK
        string schedule_id FK
    }
    %% geofence {
    %%     string id
    %%     string name
    %%     float long
    %%     float lat
    %%     float radius
    %% }
    track {
        string id
        string name
        string supervisor_id FK
        string branch_id FK
        datetime created_at
    }
    lost_item {
        string id
        string name
        string desc
        string status
        string place
        datetime lost_at
        string category
        string image_url
        boolean is_returned
    }
    found_item {
        string id
        string name
        string desc
        string status
        string place
        datetime found_at
        string category
        string image_url
        boolean is_returned
    }
    matching_record {
        string match_id
        float similarity_score
        string lost_item_id FK
        string found_item FK
        string status
    }
    role {
        string id
        string name
    }
    schedule {
        string id
        string title
        string description
        datetime start_time
        datetime end_time
        string course_id FK
        boolean is_online
        string geofence_id FK
    }
    Course {
        string id
        string name
        string instructor_id FK
        string description
        datetime created_at
    }
    Student_info{
        string id
        string track_id FK
        string laptop_uuid
        string phone_uuid
    }
    branch{
        string id
        float long
        float lat
        string location_url
        float radius
    }

    role ||--o{ User : "has"
    User ||--|| Student_info : "has"
    track ||--|{ Student_info : "enrolled in"
    %% User }|--|| branch : "belongs to"
    track }|--|| branch : "part of"
    User ||--o{ Course : "instructs"
    User ||--o{ Notification : "receives"
    User ||--o{ Attendance_record : "checks in/out"
    User ||--o{ lost_item : "loses"
    User ||--o{ found_item : "finds"
    lost_item ||--o{ matching_record : "matches"
    found_item ||--o{ matching_record : "matches"
    %% schedule ||--|| track : "belongs to"
    %% schedule ||--|| geofence : "has location"
    Attendance_record }|--|| schedule : "for session"
    Course ||--o{ schedule : "has sessions"
    track ||--o{ Course : "contains"
    %% we might want to make track - course relationship manytomany for courses that include many tracks such as soft skills and such