# Generated by Django 5.1.7 on 2025-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='program_type',
            field=models.CharField(choices=[('intensive', 'Intensive Program'), ('nine_months', '9 months')], default='nine_months', max_length=20),
        ),
    ]
