# Generated by Django 5.1.7 on 2025-03-29 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0001_initial'),
        ('users', '0005_remove_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentInfo',
        ),
    ]
