# Generated by Django 5.1.7 on 2025-04-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0002_student_is_checked_in'),
        ('attendance_management', '0002_track_program_type'),
    ]

    operations = [
    ]
