# Generated by Django 5.1.7 on 2025-04-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0005_update_schedule_primary_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_schedule',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('track', 'created_at')},
        ),
    ]
