# Generated by Django 5.1.7 on 2025-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0006_remove_schedule_unique_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateField(),
        ),
    ]
