# Generated by Django 5.1.7 on 2025-04-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0006_remove_schedule_unique_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='adjusted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
