# Generated by Django 5.1.7 on 2025-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0008_permissionrequest_adjusted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
