# Generated by Django 5.1.7 on 2025-04-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0009_applicationsetting'),
        ('attendance_management', '0010_remove_attendancerecord_early_leave_and_more'),
    ]

    operations = [
    ]
