# Generated by Django 5.1.7 on 2025-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0011_merge_20250420_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('excused_late', 'Excused Late'), ('no-check-out', 'No Check-out'), ('late-check-in_no-check-out', 'Late Check-in & No Check-out'), ('pending', 'Pending')], default='absent', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationsetting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationsetting',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_dcef13_idx'),
        ),
    ]
