# Generated by Django 5.2 on 2025-05-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0017_alter_session_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='track',
        ),
    ]
