# Generated by Django 5.2 on 2025-05-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0019_alter_schedule_track_event_schedule_event_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.DeleteModel(
            name='GuestEventRegistration',
        ),
    ]
