# Generated by Django 5.2 on 2025-05-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0020_remove_guest_event_delete_guesteventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='attendance_management.event'),
        ),
    ]
