# Generated by Django 5.2 on 2025-05-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0021_alter_schedule_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attended_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='attended_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='registered_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='registered_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
