# Generated by Django 5.1.7 on 2025-03-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('MATCHED', 'Matched'), ('CONFIRMED', 'Confirmed')], default='FOUND', max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_item_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('MATCHED', 'Matched'), ('CONFIRMED', 'Confirmed')], default='LOST', max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('lost_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_item_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedItem',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='FAILED', max_length=10)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matched_found', to='lost_and_found_system.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matched_lost', to='lost_and_found_system.lostitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['status', 'found_at'], name='lost_and_fo_status_06632c_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['status', 'lost_at'], name='lost_and_fo_status_f6be92_idx'),
        ),
        migrations.AddIndex(
            model_name='matcheditem',
            index=models.Index(fields=['lost_item', 'found_item'], name='lost_and_fo_lost_it_f75ed7_idx'),
        ),
        migrations.AddConstraint(
            model_name='matcheditem',
            constraint=models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_match'),
        ),
    ]
