# Generated by Django 5.1.7 on 2025-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found_system', '0003_alter_founditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
