# Generated by Django 5.1.7 on 2025-04-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found_system', '0004_alter_founditem_image_alter_lostitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='matched_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lost_and_found_system.matcheditem'),
        ),
    ]
