name: Build image and upload to docker hub
on:
    workflow_dispatch:
    push:
        branches:
        - staging
    pull_request:
        branches:
        - staging
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: omarderwy
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: omarderwy/trackit-app-backend:latest
